baseURL = 'https://arshjameel.com/'
languageCode = 'en-us'
title = 'Arsh Jameel'
theme = 'PaperMod'

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
    ShowBreadCrumbs = 'true'
    ShowReadingTime = 'true'
    # ShowShareButtons = 'true'
    ShowPostNavLinks = 'true'
    
    [params.homeInfoParams]
        Title = 'Hello'
        Content = 'Amongus'

[menu]
    [[menu.main]]
        name = 'Archive'
        url = '/archive/'
        weight = '10'
    [[menu.main]]
        name = 'Search'
        url = '/search/'
        weight = '20'
    [[menu.main]]
        name = 'Socials'
        identifier = 'Socials'
        url = '/socials/'
        weight = '30'
    [[menu.main]]
        name = 'Twitter'
        identifier = 'Twitter'
        parent = 'socials'
        url = 'https://twitter.com/ArshJameel_/'
        weight = '32'
    [[menu.main]]
        name = 'Instagram'
        identifier = 'Instagram'
        parent = 'socials'
        url = 'https://www.instagram.com/arshjameel_/'
        weight = '34'
    [[menu.main]]
        name = 'GitHub'
        identifier = 'GitHub'
        parent = 'socials'
        url = 'https://github.com/arshjameel'
        weight = '36'