baseURL = 'https://arshjameel.com/'
languageCode = 'en-us'
title = 'Arsh Jameel'
theme = 'PaperMod'

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
    ShowBreadCrumbs = 'true'
    ShowReadingTime = 'true'
    # ShowShareButtons = 'true'
    ShowPostNavLinks = 'true'
    
    [params.homeInfoParams]
        Title = 'Welcome!👋'
        Content = "My name is Arsh Jameel, and this is my blog. You can check out my articles on technology and self-improvement below, or get to know me better by following me on my socials linked in the header."

[menu]
    [[menu.main]]
        name = 'Archive'
        url = '/archive/'
        weight = '10'
    [[menu.main]]
        name = 'Search'
        url = '/search/'
        weight = '20'
    [[menu.main]]
        name = 'Twitter'
        identifier = 'Twitter'
        url = 'https://twitter.com/ArshJameel_/'
        weight = '30'
    [[menu.main]]
        name = 'Instagram'
        identifier = 'Instagram'
        url = 'https://www.instagram.com/arshjameel_/'
        weight = '40'
    [[menu.main]]
        name = 'GitHub'
        identifier = 'GitHub'
        url = 'https://github.com/arshjameel'
        weight = '50'