baseURL = 'https://arshjameel.com/'
languageCode = 'en-us'
title = 'Arsh Jameel'
theme = 'PaperMod'

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
    ShowReadingTime = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowRssButtonInSectionTermList = true
    ShowFullTextinRSS = true
    UseHugoToc = true
    disableSpecial1stPost = true
    showtoc = false
    tocopen = true

    ShowShareButtons = false
    disableScrollToTop = false
    comments = false
    hidemeta = false
    hideSummary = false
    ShowWordCount = false

    [params.profileMode]
        enabled = true
        title = "Arsh Jameel"
        subtitle = "Computer Systems '26 | Carleton University"
        # subtitle2 = "xyz"
        imageUrl = "/grasshopper.png/"
        imageTitle = "grasshopper"
        imageWidth = 165
        imageHeight = 165

        [[params.profileMode.buttons]]
            name = "Essays"
            url = "tags/essays"

        [[params.profileMode.buttons]]
            name = "Blogs"
            url = "tags/blogs"
            
        [[params.profileMode.buttons]]
            name = "Projects"
            url = "/projects"

        [[params.profileMode.buttons]]
            name = "About"
            url = "/about"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/arshjameel"
        weight = 10
    [[params.socialIcons]]
        name = "x"
        url = "https://twitter.com/ArshJameel_/"
        weight = 10
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/"
        weight = 10
    [[params.socialIcons]]
        name = "rss"
        url = "index.xml"
        weight = 10

[menu]
    [[menu.main]]
        name = 'Archive'
        identifier = 'Archive'
        url = '/archive/'
        weight = '10'
    [[menu.main]]
        name = 'About'
        identifier = 'About'
        url = '/about/'
        weight = '20'
    [[menu.main]]
        name = 'Explore'
        identifier = 'Search'
        url = '/search/'
        weight = '30'
