baseURL = 'https://arshjameel.com/'
languageCode = 'en-us'
title = 'Arsh Jameel'
theme = 'PaperMod'

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
    ShowReadingTime = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowRssButtonInSectionTermList = true
    ShowFullTextinRSS = true
    UseHugoToc = true
    disableSpecial1stPost = true
    showtoc = true
    tocopen = true

    ShowShareButtons = false
    disableScrollToTop = false
    comments = false
    hidemeta = false
    hideSummary = false
    ShowWordCount = false

    [params.homeInfoParams]
        Title = 'Welcome!👋'
        content = """My name is Arsh Jameel, and this is my blog. 
            You can check out my articles on technology and self-improvement 
            and follow me on my socials below."""

    [[params.socialIcons]]
        name = "twitter"
        url = "https://twitter.com/ArshJameel_/"
        weight = 10
    [[params.socialIcons]]
        name = "instagram"
        url = "https://www.instagram.com/arshjameel_/"
        weight = 10
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/arshjameel"
        weight = 10
    [[params.socialIcons]]
        name = "rss"
        url = "index.xml"
        weight = 10

[menu]
    [[menu.main]]
        name = 'Archive'
        identifier = 'Archive'
        url = '/archive/'
        weight = '10'
    [[menu.main]]
        name = 'Search'
        identifier = 'Search'
        url = '/search/'
        weight = '20'
    [[menu.main]]
        name = 'About'
        identifier = 'About'
        url = '/about/'
        weight = '30'