baseURL = 'https://arshjameel.com/'
languageCode = 'en-us'
title = 'Arsh Jameel'
theme = 'PaperMod'

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowWordCount = false
    ShowRssButtonInSectionTermList = true
    UseHugoToc = true
    disableSpecial1stPost = true
    disableScrollToTop = false
    comments = false
    hidemeta = false
    hideSummary = false
    showtoc = true
    tocopen = true
    
    [params.homeInfoParams]
        Title = 'Welcome!👋'
        content = "My name is Arsh Jameel, and this is my blog. You can check out my articles on technology and self-improvement and follow me on my socials below."
        content2 = "[Twitter](https://twitter.com/ArshJameel_/) | [Instagram](https://www.instagram.com/arshjameel_/) | [GitHub](https://github.com/arshjameel)"

[menu]
    [[menu.main]]
        name = 'Archive'
        identifier = 'Archive'
        url = '/archive/'
        weight = '10'
    [[menu.main]]
        name = 'Search'
        identifier = 'Search'
        url = '/search/'
        weight = '20'
    [[menu.main]]
        name = 'About'
        identifier = 'About'
        url = '/about/'
        weight = '30'